# @package _global_
# Task franka-lift-cube-rlinf: SKRL PPO PyTorch backend delta.
defaults:
  - /task/franka-lift-cube-rlinf/skrl.ppo@_global_
  - _self_
task:
  train_backend: torch
algo:
  agent:
    learning_epochs: 8
    mini_batches: 4
    learning_rate: 0.0003
    learning_rate_scheduler_kwargs:
      kl_threshold: 0.01
    entropy_loss_scale: 0.001
    rewards_shaper_scale: 0.01
